[package]
name = "tokio-ucx"
version = "0.1.0"
authors = ["Runji Wang <wangrunji0408@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ucx-sys = { path = "ucx-sys" }
tokio = { version = "0.2", features = ["full"] }
os_socketaddr = "0.1"
mio = "0.6"
futures = "0.3"
lazy_static = "1.4"
log = "0.4"

[dev-dependencies]
env_logger = "0.7"
