name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
    - name: Check code format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install UCX
      run: |
        sudo apt install libnuma-dev
        wget https://github.com/openucx/ucx/releases/download/v1.10.0/ucx-1.10.0.tar.gz
        tar xf ucx-1.10.0.tar.gz
        cd ucx-1.10.0 && mkdir build && cd build
        ../configure && make -j && sudo make install -j
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-features
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features
    - name: Build docs
      uses: actions-rs/cargo@v1
      with:
        command: doc
